export const COMPOUND_MONITOR_MARKERS: Record<string, { markers: string[]; note: string }> = {
  anavar: { markers: ["hdl", "ldl", "alt"], note: "Anavar commonly suppresses HDL and can elevate liver enzymes." },
  winstrol: { markers: ["hdl", "ldl", "alt", "ast"], note: "Winstrol is harsh on HDL and hepatotoxicity risk rises with dose." },
  "winstrol-inj": { markers: ["hdl", "ldl"], note: "Injectable winstrol still crushes HDL despite avoiding first-pass liver load." },
  turinabol: { markers: ["alt", "ast", "hdl"], note: "Tbol is hepatotoxic with moderate lipid impact — track ALT/AST and HDL." },
  anadrol: { markers: ["alt", "ast", "hematocrit"], note: "Anadrol can elevate liver enzymes and hematocrit." },
  dbol: { markers: ["estradiol", "alt"], note: "Dbol aromatizes heavily — watch estradiol and liver markers." },
  sdrol: { markers: ["alt", "ast", "hdl"], note: "Superdrol is highly hepatotoxic with significant lipid impact." },
  halo: { markers: ["alt", "ast", "hdl"], note: "Halotestin is hepatotoxic and harsh on lipids." },
  "test-e": { markers: ["estradiol", "hematocrit", "testosterone"], note: "Exogenous test raises E2 and hematocrit — baseline CBC and E2 matter." },
  "test-c": { markers: ["estradiol", "hematocrit", "testosterone"], note: "Exogenous test raises E2 and hematocrit — baseline CBC and E2 matter." },
  "test-p": { markers: ["estradiol", "hematocrit", "testosterone"], note: "Exogenous test raises E2 and hematocrit — baseline CBC and E2 matter." },
  "test-sus": { markers: ["estradiol", "hematocrit", "testosterone"], note: "Exogenous test raises E2 and hematocrit — baseline CBC and E2 matter." },
  deca: { markers: ["prolactin", "estradiol"], note: "19-nor compounds often elevate prolactin — monitor on-cycle." },
  npp: { markers: ["prolactin", "estradiol"], note: "19-nor compounds often elevate prolactin — monitor on-cycle." },
  "tren-a": { markers: ["prolactin", "alt", "hdl"], note: "Tren affects prolactin, lipids, and liver stress — broad panel recommended." },
  "tren-e": { markers: ["prolactin", "alt", "hdl"], note: "Tren affects prolactin, lipids, and liver stress — broad panel recommended." },
  eq: { markers: ["hematocrit", "hemoglobin"], note: "EQ commonly elevates hematocrit — monitor CBC on-cycle." },
  ment: { markers: ["prolactin", "estradiol"], note: "MENT is a potent 19-nor — prolactin and E2 monitoring is critical." },
};