import type { ThemePresetId } from "@/lib/themes";

export type ThemeGroupId = "all" | "neutral" | "classic" | "vivid" | "wild";

export const THEME_GROUPS: { id: ThemeGroupId; label: string; presets: ThemePresetId[] }[] = [
  {
    id: "neutral",
    label: "Neutral",
    presets: [
      "graphite",
      "slate",
      "charcoal",
      "stone",
      "ash",
      "ink",
      "bone",
      "pearl",
      "mist",
      "frost-plain",
    ],
  },
  {
    id: "classic",
    label: "Classic",
    presets: [
      "crimson",
      "ember",
      "violet",
      "ocean",
      "rose-gold",
      "matrix",
      "sage",
      "mint",
      "lavender",
      "copper",
      "gold",
      "coral",
      "berry",
      "teal",
      "indigo",
    ],
  },
  {
    id: "vivid",
    label: "Vivid",
    presets: [
      "sunset",
      "aurora",
      "wine",
      "midnight",
      "jungle",
      "honey",
      "arctic-frost",
      "solar-flare",
      "deep-void",
      "halotestin",
      "blood-moon",
      "toxic",
    ],
  },
  {
    id: "wild",
    label: "Wild",
    presets: [
      "cyberpunk-neon",
      "vaporwave",
      "synthwave",
      "inferno",
      "plasma",
      "hologram",
      "laser",
      "radioactive",
      "supernova",
      "neon-noir",
      "electric-dream",
      "abyss",
      "glitch",
      "chaos",
    ],
  },
];